# Generated by Django 2.2.10 on 2021-05-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='choice',
            name='lock_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='points',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='max_points',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=4096),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
